import { Header } from "@/components/header"
import { Footer } from "@/components/footer"

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main className="pt-32 pb-20">
        <div className="container mx-auto px-4 max-w-4xl">
          <h1 className="text-5xl font-bold text-foreground mb-8">Terms & Conditions</h1>

          <div className="prose prose-invert max-w-none space-y-8 text-foreground/80">
            <section>
              <h2 className="text-2xl font-bold text-foreground mb-4">1. Acceptance of Terms</h2>
              <p>
                By accessing and using HeHo, you accept and agree to be bound by the terms and provision of this
                agreement. If you do not agree to abide by the above, please do not use this service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-foreground mb-4">2. User Responsibilities</h2>
              <p>You are responsible for:</p>
              <ul className="list-disc pl-6 space-y-2 mt-2">
                <li>Maintaining the confidentiality of your OpenRouter API key</li>
                <li>Maintaining the confidentiality of your Supabase credentials</li>
                <li>All activities that occur under your account</li>
                <li>Ensuring your use complies with all applicable laws</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-foreground mb-4">3. AI & OpenRouter</h2>
              <p>
                HeHo uses OpenRouter to power AI responses. You are responsible for complying with OpenRouter's Terms of
                Service. AI responses are generated by third-party models and may not always be accurate.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-foreground mb-4">4. Data & Privacy</h2>
              <p>
                HeHo stores only authentication data in our database. Your chatbot data and database connections are
                stored in your own Supabase instance. We do not share your data with third parties except as necessary
                for operation (e.g., sending requests to OpenRouter for AI processing).
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-foreground mb-4">5. Prohibited Use</h2>
              <p>You may not use HeHo for:</p>
              <ul className="list-disc pl-6 space-y-2 mt-2">
                <li>Creating illegal content</li>
                <li>Generating misinformation or disinformation</li>
                <li>Scraping or harvesting personal data</li>
                <li>Harassment or abuse</li>
                <li>Attempting to circumvent usage limits</li>
                <li>Any activity that violates OpenRouter's terms</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-foreground mb-4">6. Limitation of Liability</h2>
              <p>HeHo is provided on an "as-is" basis. We are not responsible for:</p>
              <ul className="list-disc pl-6 space-y-2 mt-2">
                <li>Data loss or corruption</li>
                <li>AI model hallucinations or errors</li>
                <li>Third-party service outages (OpenRouter, Supabase)</li>
                <li>Your use of the service in violation of these terms</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-foreground mb-4">7. Changes to Service</h2>
              <p>
                HeHo reserves the right to modify or discontinue the service at any time. We will provide 30 days notice
                for major changes that negatively impact functionality.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-foreground mb-4">8. Termination</h2>
              <p>
                We may terminate your account if you violate these terms or engage in prohibited use. You may delete
                your account at any time from your account settings.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold text-foreground mb-4">9. Contact</h2>
              <p>For questions about these terms, please contact: legal@heho.dev</p>
            </section>

            <div className="text-sm text-muted-foreground mt-12">
              <p>Last updated: January 2025</p>
            </div>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  )
}
