import { createServerClient } from '@supabase/ssr'
import { cookies } from 'next/headers'
import { NextResponse } from 'next/server'
import { createClient } from '@supabase/supabase-js'

const EDITABLE_TABLES = ['products', 'leads', 'customer_queries', 'sales'];

// Helper function to get a Supabase client authenticated for the current user's database.
async function getUserSupabaseClient() {
  const cookieStore = cookies()

  // First, create a client to our app's database to get user details.
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        get(name: string) {
          return cookieStore.get(name)?.value
        },
      },
    }
  )

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) {
    throw new Error('Unauthorized: You must be logged in to perform this action.');
  }

  // Fetch the user's credentials for their own Supabase instance.
  const { data: userData, error: userError } = await supabase
    .from('users')
    .select('supabase_url, supabase_key_encrypted')
    .eq('id', user.id)
    .single()

  if (userError || !userData) {
    throw new Error('Could not retrieve your Supabase credentials. Please verify them in the settings.');
  }

  const { supabase_url, supabase_key_encrypted } = userData

  if (!supabase_url || !supabase_key_encrypted) {
    throw new Error('User has not configured their Supabase connection in settings.');
  }

  // Return a new client connected to the user's database.
  return createClient(supabase_url, supabase_key_encrypted);
}

export async function POST(request: Request) {
  const { tableName, action, payload } = await request.json();

  if (!tableName || !EDITABLE_TABLES.includes(tableName)) {
      return NextResponse.json({ error: 'This table is not editable or does not exist.' }, { status: 403 });
  }

  try {
    const userSupabase = await getUserSupabaseClient();

    switch(action) {
      case 'ADD_ROW': {
        const { newRow } = payload;
        // The 'id' column is auto-generated by the database, so we must not send it.
        const { id, ...insertData } = newRow;
        const { data, error } = await userSupabase
          .from(tableName)
          .insert([insertData])
          .select()
          .single(); 

        if (error) throw error;
        return NextResponse.json({ message: 'Row added successfully', data });
      }

      case 'UPDATE_ROW': {
        const { rowId, updatedData } = payload;
        const { id, ...updateData } = updatedData; // Never allow updating the id.
        const { data, error } = await userSupabase
          .from(tableName)
          .update(updateData)
          .eq('id', rowId)
          .select()
          .single();

        if (error) throw error;
        return NextResponse.json({ message: 'Row updated successfully', data });
      }

      case 'DELETE_ROW': {
        const { rowId } = payload;
        const { error } = await userSupabase
          .from(tableName)
          .delete()
          .eq('id', rowId);

        if (error) throw error;
        return NextResponse.json({ message: 'Row deleted successfully' });
      }

      default:
        return NextResponse.json({ error: 'Invalid action specified.' }, { status: 400 });
    }

  } catch (err: any) {
    console.error(`Error in /api/database/edit (Action: ${action}, Table: ${tableName}):`, err);
    return NextResponse.json({ error: err.message || 'An unexpected error occurred.' }, { status: 500 });
  }
}
